version: '3.4'

services:
  frontend:
    build: .\front_task1
    container_name: frontend
    depends_on: [backend]
    ports: 
      - "5000:5000"
  backend:
    build: ./back_task1
    container_name: backend
    ports:
        - "5002:5002"
  
